name: GaymersPronouns
version: '1.2.1'
main: coolepicgaymer.gaymerspronouns.GaymersPronouns
softdepend: [ PlaceholderAPI ]
authors: [ coolepicgaymer ]
api-version: 1.16
description: A simple, yet very customizable Minecraft chat plugin that adds pronouns.
commands:
  pronouns:
    aliases: [ pronoun ]
    permission: gaymerspronouns.use
    description: Pick your pronouns or see others' pronouns.
  gaymerspronouns:
    aliases: [ gp ]
    permission: gaymerspronouns.admin
    description: Admin command for GaymersPronouns.
permissions:
  gaymerspronouns.*:
    description: Allows the player to do anything with the plugin.
    default: op
    children:
      gaymerspronouns.admin: true
      gaymerspronouns.admin.assign: true
      gaymerspronouns.admin.configure: true
      gaymerspronouns.admin.reload: true
      gaymerspronouns.admin.database: true
  gaymerspronouns.admin:
    description: Allows the player to use the admin command.
  gaymerspronouns.admin.assign:
    description: Allows the player to assign pronouns to others.
  gaymerspronouns.admin.configure:
    description: Allows the player to configure the plugin from in-game.
  gaymerspronouns.admin.reload:
    description: Allows the player to reload the plugin.
  gaymerspronouns.admin.database:
    description: Allows the player to use database commands.
  gaymerspronouns.use:
    default: true
    description: Allows the player to pick their own pronouns and see others' pronouns.