name: GaymersPronouns
version: '${project.version}'
main: coolepicgaymer.gaymerspronouns.GaymersPronouns
softdepend: [ PlaceholderAPI ]
authors: [ coolepicgaymer ]
api-version: 1.16
description: A simple, yet very customizable Minecraft chat plugin that adds pronouns.
commands:
  pronouns:
    aliases: [ pronoun ]
    description: Pick your pronouns.
