name: GaymersPronouns
version: '${project.version}'
main: coolepicgaymer.gaymerspronouns.GaymersPronouns
api-version: 1.18
softdepend: [ PlaceholderAPI ]
authors: [ coolepicgaymer ]
description: A simple, yet very customizable Minecraft chat plugin that adds pronouns.
commands:
  pronouns:
    aliases: [ pronoun ]
    description: Pick your pronouns.
